version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    depends_on:
      - db
    image: yw/whatsinme-api
    restart: always
    ports:
      - 5003:80
    environment:
      SERVER_PORT: 80
      DB_URL: jdbc:postgresql://db/postgres
      DB_USER: postgres
      DB_PASS: postgres
  app:
    depends_on:
      - api
    image: yw/whatsinme-app
    restart: always
    ports:
      - 5002:80
